import raw from "@data/goldens.json";

/**
 * Corpus facts, snapshotted from the committed artifacts.
 *
 * These figures used to be inline literals in the tests -- "grand total is
 * 241739.67", "latest period is 2026-06", "220 statements" -- spread across
 * 31 test files. Importing one month of statements moved every one of them
 * and failed 145 tests, and the only way through was to hand-edit 145
 * literals. Hand-editing a golden is where a wrong number gets blessed by
 * accident, and doing it monthly guarantees it eventually happens.
 *
 * So the figures live here instead, in ONE file, regenerated by an explicit
 * `bun run goldens` and nothing else. A test that reads a golden still fails
 * on a code regression exactly as it did before, because the golden only
 * moves when the command is run; what it no longer does is fail on a
 * legitimate data import. The monthly diff is one file, and it is reviewable
 * because every figure sits beside the others that moved with it.
 *
 * `bun run goldens` computes each figure with the SAME production function
 * the test calls (see `src/tools/goldens.ts`), so a golden can never encode
 * a figure the pipeline does not actually produce. That is also the limit of
 * what this proves: a regression that lands in the pipeline and is then
 * blessed by a `bun run goldens` run in the same breath is invisible here.
 * Regenerate goldens in a commit that changes DATA, and read the diff.
 */
export interface Goldens {
  /** The corpus these figures were snapshotted from. */
  corpus: {
    /** Statements in the committed datastore, after version deduplication. */
    statementCount: number;
    /** Files in the source directory that parse to those statements. */
    sourceFileCount: number;
    accountCount: number;
    /**
     * Accounts that count toward the portfolio total. Fewer than
     * `accountCount`: Chequing is money held rather than invested, and the
     * spousal RRSP is the spouse's asset. This is the figure a readout means
     * by "N of M accounts reported this month".
     */
    countedAccountCount: number;
    /** Latest period across `inTotals` accounts -- the date the headline figure carries. */
    latestPeriod: string;
    /** The first period any counted account reports. */
    firstPeriod: string;
  };
  portfolio: {
    /** Registration-lens grand total; all three lenses must agree with it. */
    total: number;
    bookCost: number;
    gain: number;
    /** `gain / bookCost`, the share the headline prints. */
    gainShare: number;
    /** Months in `buildPortfolioSeries` over the whole corpus. */
    seriesPointCount: number;
  };
  reconciliation: {
    findingCount: number;
    acknowledgedCount: number;
    unacknowledgedCount: number;
    /** Checks of the acknowledged findings, sorted -- the acknowledgement roster. */
    acknowledgedChecks: string[];
    /** The `statement-arithmetic` group, the corpus's one large collapsed group. */
    statementArithmeticCount: number;
  };
  /**
   * Latest market/book/gain per group, keyed `<lens>:<group label>`, plus the
   * first and last period the group's own value history covers -- which is
   * not the portfolio's range, since accounts open at different times.
   */
  groups: Record<
    string,
    { market: number; book: number; gain: number; firstPeriod: string; lastPeriod: string }
  >;
  /**
   * Account-lens group labels whose latest gain is negative, sorted. Empty
   * when the corpus holds no loss at all, which is a real state: the two
   * losses that existed at 2026-06 (Private Market Fund -$3.16, Crypto -$45.04)
   * both turned positive at 2026-07. A test that pins a loss figure as a
   * constant becomes unsatisfiable the month the market moves, so the loss
   * RENDERING is proven on a fixture and this records only whether the real
   * corpus currently exercises that path as well.
   */
  lossGroups: string[];
  /** Latest stated market value per account, keyed by 4-char shortId. */
  accounts: Record<string, number>;
  /**
   * Per-account projection allocation, keyed by shortId, for the accounts the
   * projection covers. `share` is the group's recent contribution split and
   * `opening` the account's latest stated market value, so both move with an
   * import.
   */
  allocations: Record<string, { group: string; share: number; opening: number }>;
  /**
   * The monthly-return series, per account shortId: months present, months
   * that actually carry a rate, and that account's own rate extent (null when
   * it has no computable month at all). An account gains a plotted month with
   * every import, so every one of these moves.
   */
  returns: Record<string, { points: number; plotted: number; extent: [number, number] | null }>;
  /**
   * How many accounts the Growth tab's returns grid actually draws --
   * `chartedReturnAccounts` over the corpus, so a Chequing account or one
   * cut back to zero plotted points never inflates this count.
   */
  returnsChartedCount: number;
  /** Total plotted dots across every CHARTED account's return chart, matching the grid, not the whole corpus. */
  returnsChartedPlottedTotal: number;
  cashflow: {
    /** The last month of the cashflow series. */
    period: string;
    deposits: number;
    withdrawals: number;
    /** Accounts reporting a cashflow figure in that last month. */
    accountCount: number;
  };
  fittedRate: {
    /** Annualized rate fitted from the market-value history. */
    rate: number;
    months: number;
    countedAccounts: number;
    /** Links fitted; one short of `months - 1` because 2023-06 opens at a real $0. */
    steps: number;
  };
  projection: {
    /** Terminal value at the default 6%. */
    defaultRateEndValue: number;
    /** Terminal value at `fittedRate.rate`. */
    fittedRateEndValue: number;
    /** The period the stated half ends and the projected half begins. */
    seamPeriod: string;
    /** Accounts the projection cannot forecast, and the money in them. */
    uncoveredAccountCount: number;
    uncoveredValue: number;
    /** The year the FHSA must close, and the balance it holds the year its cap fills. */
    fhsaCloseYear: string;
    fhsaCapYear: string;
    fhsaValueAtCapYear: number;
    /** The plan's own retirement year, birthYear plus retirementAge. */
    retirementYear: number;
    /** The default-selection base scenario's balance at the retirement year, today's and future dollars. */
    retirementReal: number;
    retirementNominal: number;
    /** The plan's withdrawal rate applied monthly to the real retirement balance. */
    retirementMonthlyIncome: number;
    /** The first year the base scenario reaches each milestone, in today's dollars, or null. */
    milestone500kYear: string | null;
    milestone1mYear: string | null;
  };
  rooms: {
    /** Each projected group's opening balance -- its accounts' latest stated market values. */
    opening: Record<string, number>;
    /** Lifetime contributions to date, by wrapper. */
    lifetimeContributed: Record<string, number>;
    /** Basic CESG room accrued from the beneficiary's birth year. */
    cesgRoomAccrued: number;
    /**
     * RESP lifetime contributions counted from tagged `CONT` rows ALONE.
     * Lower than `lifetimeContributed.RESP`, which also folds in `DEP` rows,
     * and the gap between them is the trap `inputs.test.ts` exists to hold
     * open: CRA counts every dollar into an RESP against the lifetime cap
     * however it arrived, so reading tagged contributions alone undercounts.
     */
    respFromContRowsOnly: number;
    /** RRSP assessed room remaining in the projection's start year. */
    rrspAssessedRemaining: number;
    /** Contributions in the start year, by wrapper. */
    contributed: Record<string, number>;
    /** The assessed RRSP line the bar is drawn against. */
    rrspAssessedLimit: number;
    /** Lifetime RESP contributed, read from deposits rather than CONT rows. */
    respLifetimeContributed: number;
    /** CESG already received. */
    cesgReceived: number;
    /** The slice of the RRSP's used room contributed to a spousal RRSP. */
    rrspSpousalUsed: number;
  };
  runway: {
    /** CESG the projection ends up claiming, short of the $7,200 cap. */
    cesgClaimed: number;
    /** The unclaimed remainder, forfeited when the beneficiary ages out. */
    cesgForfeited: number;
    /**
     * Lifetime room still unfilled after a ONE-year projection window, per
     * wrapper. This is what makes `capBound`'s never-reached branch
     * reachable over the real corpus, and it moves with every month of
     * contributions, which is why it is a golden rather than a literal.
     */
    leftoverAfterOneYear: Record<string, number>;
  };
  /**
   * Goal verdicts at the default 6%, keyed by goal id, over `GOLDEN_GOALS`
   * (the two shipped goals plus the fixture goals the tests need to reach
   * the shortfall and room-blocked branches).
   */
  goals: Record<
    string,
    {
      projected: number | null;
      gap: number | null;
      monthlyToClose: number | null;
      blocked: string | null;
      coveredCount: number;
      uncoveredCount: number;
    }
  >;
  /**
   * The stretch goal's shortfall solved at a ZERO return rate, where the
   * textbook growth-factor formula would divide by zero. Recorded separately
   * because it is the one figure the tests take off a 0% projection.
   */
  zeroRateStretchAnnualToClose: number;
  income: {
    /** The latest income year the tax view shows. */
    year: number;
    canadianDistributions: number;
    foreignDividends: number;
    foreignTaxWithheld: number;
    interest: number;
    realizedGain: number;
    costUnknownSales: number;
    rrspDeduction: number;
  };
  /**
   * `analytics.income["2025"]` and `["2026"]`, verbatim -- the corpus
   * regression pin for `buildIncome`'s realized gains fix. Both years come
   * straight off the same `analytics.json` the dashboard reads, never
   * recomputed here, so a regression in the pipeline shows up as a red
   * test rather than a `bun run goldens` run quietly re-blessing it.
   */
  incomeByYear: Record<
    "2025" | "2026",
    {
      interest: number;
      canadianDistributions: number;
      foreignDividends: number;
      foreignTaxWithheld: number;
      realizedGains: number;
      costUnknownSales: number;
    }
  >;
  /**
   * `incomeByYear`'s totals for 2025 and 2026, computed by that same
   * function over the committed `analytics.json` -- dividends, interest,
   * securities lending, foreign withholding tax, fees, FX conversion counts
   * and the CAD side amount converted, over the `inTotals` accounts only.
   * `chequingInterestByYear` and `feeReconciliationGapsByYear` are separate
   * facts the Income tab states apart from these totals: chequing interest
   * never counts toward the portfolio, and a fee reconciliation gap is a
   * data limitation, not an income or cost figure.
   */
  incomeCosts: {
    byYear: Record<
      "2025" | "2026",
      {
        dividends: number;
        interest: number;
        lendingIncome: number;
        withholdingTax: number;
        fees: number;
        fxConversions: number;
        fxConversionAmount: number;
      }
    >;
    /** Total chequing interest (kind `Chequing`, never `inTotals`), summed across every chequing account. */
    chequingInterestByYear: Record<"2025" | "2026", number>;
    /** `feeReconciliationGaps`, by year -- expected empty for 2025 and one account for 2026 (the trading cost gap). */
    feeReconciliationGapsByYear: Record<"2025" | "2026", { label: string; gap: number }[]>;
  };
  /** `monthReview` at the latest reviewable period, computed by that same function. */
  month: {
    period: string;
    /** Full portfolio end minus full portfolio start (both nullable-safe). */
    change: number;
    /** Comparable-subset deposits, see `monthReview`'s own doc. */
    netDeposits: number;
    growth: number;
    missingValue: number;
  };
}

function isGoldens(value: unknown): value is Goldens {
  if (typeof value !== "object" || value === null) return false;
  const c = value as Record<string, unknown>;
  return (
    typeof c.corpus === "object" &&
    typeof c.portfolio === "object" &&
    typeof c.reconciliation === "object" &&
    typeof c.groups === "object" &&
    Array.isArray(c.lossGroups) &&
    typeof c.accounts === "object" &&
    typeof c.allocations === "object" &&
    typeof c.returns === "object" &&
    typeof c.returnsChartedCount === "number" &&
    typeof c.returnsChartedPlottedTotal === "number" &&
    typeof c.cashflow === "object" &&
    typeof c.fittedRate === "object" &&
    typeof c.projection === "object" &&
    typeof c.rooms === "object" &&
    typeof c.runway === "object" &&
    typeof c.goals === "object" &&
    typeof c.zeroRateStretchAnnualToClose === "number" &&
    typeof c.income === "object" &&
    typeof c.incomeByYear === "object" &&
    typeof c.incomeCosts === "object" &&
    typeof c.month === "object"
  );
}

/**
 * Throws rather than casting: a goldens file written by an older generator,
 * missing a section a test reads, would otherwise surface as `undefined`
 * inside an assertion, which reads as a failing figure rather than a stale
 * artifact.
 */
export function loadGoldens(): Goldens {
  if (!isGoldens(raw)) {
    throw new Error("data/goldens.json is missing a section; run bun run goldens");
  }
  return raw;
}

export const GOLDENS: Goldens = loadGoldens();

/** The group golden for one lens and label, or a throw naming what is missing. */
export function groupGolden(lens: string, label: string): Goldens["groups"][string] {
  const key = `${lens}:${label}`;
  const found = GOLDENS.groups[key];
  if (!found) {
    throw new Error(`no group golden for ${key}; run bun run goldens`);
  }
  return found;
}

/** The latest market value for one account shortId, or a throw naming it. */
export function accountGolden(shortId: string): number {
  const found = GOLDENS.accounts[shortId];
  if (found === undefined) {
    throw new Error(`no account golden for ${shortId}; run bun run goldens`);
  }
  return found;
}
