/** tracking.md, generated: deadlines and open items as an Obsidian checklist, from the same data as the pages. */

import { plainDate } from "./format";
import { PAID_NOT_FILED, isLive, sortItems } from "./status";
import type { TaxData } from "./types";

export function trackingMarkdown(d: TaxData): string {
  const deadlines = d.filings
    .flatMap((f) => [
      f.due
        ? {
            date: f.due,
            text: `${PAID_NOT_FILED.includes(f.kind) ? "Pay" : "File"} ${f.title}`,
            done: f.status === "filed" || f.status === "assessed",
          }
        : null,
      f.payment_due && f.payment_due !== f.due
        ? {
            date: f.payment_due,
            text: `Pay ${f.title}`,
            done: f.status === "filed" || f.status === "assessed",
          }
        : null,
    ])
    .filter((x): x is NonNullable<typeof x> => x !== null && x.date >= d.meta.as_of)
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((x) => `- [${x.done ? "x" : " "}] ${plainDate(x.date)}: ${x.text}`);
  const live = sortItems(d.openItems.filter(isLive)).map(
    (i) =>
      `- [ ] ${i.title} (${i.owner}${i.due ? `, by ${plainDate(i.due)}` : ""}${i.status === "waiting" ? ", waiting" : ""})`,
  );
  const closed = d.openItems
    .filter((i) => !isLive(i))
    .map((i) => `- [x] ${i.title}${i.closed_on ? ` (closed ${plainDate(i.closed_on)})` : ""}`);
  return `---
title: Taxes tracking
tags: [personal/taxes]
created: 2026-10-07
updated: ${d.meta.as_of}
status: active
type: reference
personal: taxes
---

# Taxes tracking

Generated by \`scripts/\` from \`data/\`. Edit \`data/open-items.json\` or \`data/filings.json\`, then \`bun run build\`.

## Coming deadlines

${deadlines.join("\n") || "- none"}

## Open

${live.join("\n") || "- nothing open"}

## Closed

${closed.join("\n") || "- none yet"}
`;
}
