import { join } from "node:path";
import rawDatastore from "@data/datastore.json";
import { type Coverage, buildCoverage } from "../analytics/coverage";
import type { Datastore } from "../store/datastore";

const ROOT = join(import.meta.dir, "..", "..", "..");
export const TRACKER_PATH = join(ROOT, "tracking.md");
export const COVERAGE_PATH = join(ROOT, "data", "coverage.json");

export function renderCoverageJson(c: Coverage): string {
  return `${JSON.stringify(c, null, 2)}\n`;
}

function headline(c: Coverage): string {
  if (c.latestComplete === null) return "No month yet has a statement for every open account.";
  const behind = c.accounts.filter((a) => a.lastPeriod < c.latestPeriod).map((a) => a.label);
  const open = c.months.find((m) => m.period === c.latestComplete)?.expected ?? 0;
  const lines = [
    `Latest complete month: **${c.latestComplete}**, with all ${open} open accounts reported.`,
  ];
  if (c.latestComplete !== c.latestPeriod) {
    lines.push(`Latest month with any statement: ${c.latestPeriod}. Behind: ${behind.join(", ")}.`);
  }
  return lines.join("\n\n");
}

export function renderTracker(c: Coverage): string {
  const updated = c.generated.slice(0, 10);
  const accountRows = c.accounts.map(
    (a) =>
      `| ${a.label} | ${a.kind} | ${a.inTotals ? "yes" : "no"} | ${a.firstPeriod} | ${a.lastPeriod} | ${a.monthCount} | ${a.missing.length === 0 ? "none" : a.missing.join(", ")} |`,
  );
  const monthRows = c.months.map(
    (m) =>
      `| ${m.period} | ${m.present} of ${m.expected} | ${m.missing.length === 0 ? "complete" : m.missing.join(", ")} |`,
  );
  return [
    "---",
    "title: Statement coverage",
    "tags: [personal/investments, tracking]",
    "created: 2026-09-26",
    `updated: ${updated}`,
    "status: active",
    "type: reference",
    "personal: investments",
    "---",
    "",
    "# Statement coverage",
    "",
    "Generated by `bun run tracker` from `data/datastore.json`, which is the permanent archive of every imported statement. Do not edit by hand; `bun run check` fails when this file is stale.",
    "",
    headline(c),
    "",
    "## By account",
    "",
    "Missing counts every month from the account's first statement to the latest month in the archive.",
    "",
    "| Account | Kind | In totals | First | Latest | Months | Missing |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...accountRows,
    "",
    "## By month",
    "",
    "An account is expected from its first statement onward.",
    "",
    "| Month | Accounts | Missing |",
    "| --- | --- | --- |",
    ...monthRows,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const coverage = buildCoverage(rawDatastore as Datastore);
  await Bun.write(TRACKER_PATH, renderTracker(coverage));
  await Bun.write(COVERAGE_PATH, renderCoverageJson(coverage));
  console.log(
    `wrote tracking.md and coverage.json: latest complete month ${coverage.latestComplete ?? "none"}, ` +
      `latest statement ${coverage.latestPeriod}, ${coverage.accounts.length} accounts`,
  );
}
